spring:
  datasource:
    url: ${JDBC_HOST:jdbc:mysql://localhost:3306/feedbackPortal?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8}
    username: ${JDBC_USERNAME:root}
    password: ${JDBC_PASSWORD:igdefault}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    view:
      prefix:/WEB-INF/views/
      suffix:.jsp